global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'elysia'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'worker-events'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9101']

  - job_name: 'worker-outbox'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9102']
